name: as_hokme
description: "A new Flutter project."

publish_to: "none"

version: 1.0.3+3

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  url_launcher: ^6.3.1
  get_storage: ^2.1.1
  audioplayers: ^6.4.0
  integration_test_preview: ^0.1.0
  confetti: ^0.8.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/songs/
    - assets/fonts/
    - assets/drawables/

  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-Regular.ttf
        - asset: assets/fonts/Vazirmatn-Bold.ttf
          weight: 700
